### ISSUE TITLE
Possibly include in Adafruit_CircuitPython_ESP32SPI Library

### ISSUE THREAD

**Issue by brentru** [beachbc/esp32spi_mqtt#1]
This library would be a great addition to the library it includes - CircuitPython_ESP32SPI (https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/tree/master/adafruit_esp32spi)!

Would you be open to submitting a pull request to add it into the library as a file - `adafruit_esp32spi_mqtt.py`? 

EDIT: a better idea would be making a new library which you can pass a `socket`-compatible device to, for ethernet compatibility in the future.

**Comment by beachbc** [comment]
Of course!  That would certainly be the best option.  I'll look into it soon.

**Comment by brentru** [comment]
@beachbc We've split development of this off into a a sep. library since I posted this. MiniMQTT - our intention is making it network-interface-hardware-agnostic (doesn't just need to be ESP32SPI). Lots of new methods/helpers/stricter adherence to the MQTT spec have been added since. Thank you for this repo!

src - https://github.com/brentru/Adafruit_CircuitPython_MiniMQTT/

**Comment by beachbc** [comment]
Oh great!  I'd be happy to start using/contributing to that one instead and take this one down!

**Comment by brentru** [comment]
It's not ready for public contributions just yet (still working on some issues and building out tests) but will be located on the adafruit/ repo when it's ready.

You don't need to take this one down, though that's up to you.

**Comment by beachbc** [comment]
I started watching your Adafruit_CircuitPython_MiniMQTT repo.  Hopefully I get a notification when it's ready. Cheers!
